language: node_js

services:
  - mongodb

node_js:
  - '18'
  - '20'

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

script:
  - npm test

notifications:
  email:
    on_success: change
    on_failure: always